package day9;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashSet;
import java.util.Set;

import static day9.Ex1.countTailPosition;
import static org.junit.jupiter.api.Assertions.assertNotNull;

public class Ex2 {

    @Test
    public void ex2() throws IOException {
        Path path = Paths.get("src/test/resources/day9.txt");

        var read = Files.readAllLines(path);
        assertNotNull(read);

        Set<Ex1.Point> visitedByTail = new HashSet<>();
        var startPoint = new Ex1.Point(0, 0);
        visitedByTail.add(startPoint);
        var headX = 0;
        var headY = 0;
        var middle1X = 0;
        var middle1Y = 0;
        var middle2X = 0;
        var middle2Y = 0;
        var middle3X = 0;
        var middle3Y = 0;
        var middle4X = 0;
        var middle4Y = 0;
        var middle5X = 0;
        var middle5Y = 0;
        var middle6X = 0;
        var middle6Y = 0;
        var middle7X = 0;
        var middle7Y = 0;
        var middle8X = 0;
        var middle8Y = 0;
        var tailX = 0;
        var tailY = 0;
        for (var r : read) {
            var split = r.split(" ");
            var direction = split[0];
            var steps = Integer.parseInt(split[1]);

            switch (direction) {
                case "L" -> {
                    for (int i = 0; i < steps; i++) {
                        headX -= 1;
                        var middle1Point = countTailPosition(headX, headY, middle1X, middle1Y);
                        middle1X = middle1Point.x;
                        middle1Y = middle1Point.y;
                        var middle2Point = countTailPosition(middle1X, middle1Y, middle2X, middle2Y);
                        middle2X = middle2Point.x;
                        middle2Y = middle2Point.y;
                        var middle3Point = countTailPosition(middle2X, middle2Y, middle3X, middle3Y);
                        middle3X = middle3Point.x;
                        middle3Y = middle3Point.y;
                        var middle4Point = countTailPosition(middle3X, middle3Y, middle4X, middle4Y);
                        middle4X = middle4Point.x;
                        middle4Y = middle4Point.y;
                        var middle5Point = countTailPosition(middle4X, middle4Y, middle5X, middle5Y);
                        middle5X = middle5Point.x;
                        middle5Y = middle5Point.y;
                        var middle6Point = countTailPosition(middle5X, middle5Y, middle6X, middle6Y);
                        middle6X = middle6Point.x;
                        middle6Y = middle6Point.y;
                        var middle7Point = countTailPosition(middle6X, middle6Y, middle7X, middle7Y);
                        middle7X = middle7Point.x;
                        middle7Y = middle7Point.y;
                        var middle8Point = countTailPosition(middle7X, middle7Y, middle8X, middle8Y);
                        middle8X = middle8Point.x;
                        middle8Y = middle8Point.y;
                        var tailPoint = countTailPosition(middle8X, middle8Y, tailX, tailY);
                        tailX = tailPoint.x;
                        tailY = tailPoint.y;
                        visitedByTail.add(tailPoint);
                    }
                }
                case "R" -> {
                    for (int i = 0; i < steps; i++) {
                        headX += 1;
                        var middle1Point = countTailPosition(headX, headY, middle1X, middle1Y);
                        middle1X = middle1Point.x;
                        middle1Y = middle1Point.y;
                        var middle2Point = countTailPosition(middle1X, middle1Y, middle2X, middle2Y);
                        middle2X = middle2Point.x;
                        middle2Y = middle2Point.y;
                        var middle3Point = countTailPosition(middle2X, middle2Y, middle3X, middle3Y);
                        middle3X = middle3Point.x;
                        middle3Y = middle3Point.y;
                        var middle4Point = countTailPosition(middle3X, middle3Y, middle4X, middle4Y);
                        middle4X = middle4Point.x;
                        middle4Y = middle4Point.y;
                        var middle5Point = countTailPosition(middle4X, middle4Y, middle5X, middle5Y);
                        middle5X = middle5Point.x;
                        middle5Y = middle5Point.y;
                        var middle6Point = countTailPosition(middle5X, middle5Y, middle6X, middle6Y);
                        middle6X = middle6Point.x;
                        middle6Y = middle6Point.y;
                        var middle7Point = countTailPosition(middle6X, middle6Y, middle7X, middle7Y);
                        middle7X = middle7Point.x;
                        middle7Y = middle7Point.y;
                        var middle8Point = countTailPosition(middle7X, middle7Y, middle8X, middle8Y);
                        middle8X = middle8Point.x;
                        middle8Y = middle8Point.y;
                        var tailPoint = countTailPosition(middle8X, middle8Y, tailX, tailY);
                        tailX = tailPoint.x;
                        tailY = tailPoint.y;
                        visitedByTail.add(tailPoint);
                    }
                }
                case "U" -> {
                    for (int i = 0; i < steps; i++) {
                        headY += 1;
                        var middle1Point = countTailPosition(headX, headY, middle1X, middle1Y);
                        middle1X = middle1Point.x;
                        middle1Y = middle1Point.y;
                        var middle2Point = countTailPosition(middle1X, middle1Y, middle2X, middle2Y);
                        middle2X = middle2Point.x;
                        middle2Y = middle2Point.y;
                        var middle3Point = countTailPosition(middle2X, middle2Y, middle3X, middle3Y);
                        middle3X = middle3Point.x;
                        middle3Y = middle3Point.y;
                        var middle4Point = countTailPosition(middle3X, middle3Y, middle4X, middle4Y);
                        middle4X = middle4Point.x;
                        middle4Y = middle4Point.y;
                        var middle5Point = countTailPosition(middle4X, middle4Y, middle5X, middle5Y);
                        middle5X = middle5Point.x;
                        middle5Y = middle5Point.y;
                        var middle6Point = countTailPosition(middle5X, middle5Y, middle6X, middle6Y);
                        middle6X = middle6Point.x;
                        middle6Y = middle6Point.y;
                        var middle7Point = countTailPosition(middle6X, middle6Y, middle7X, middle7Y);
                        middle7X = middle7Point.x;
                        middle7Y = middle7Point.y;
                        var middle8Point = countTailPosition(middle7X, middle7Y, middle8X, middle8Y);
                        middle8X = middle8Point.x;
                        middle8Y = middle8Point.y;
                        var tailPoint = countTailPosition(middle8X, middle8Y, tailX, tailY);
                        tailX = tailPoint.x;
                        tailY = tailPoint.y;
                        visitedByTail.add(tailPoint);
                    }
                }
                case "D" -> {
                    for (int i = 0; i < steps; i++) {
                        headY -= 1;
                        var middle1Point = countTailPosition(headX, headY, middle1X, middle1Y);
                        middle1X = middle1Point.x;
                        middle1Y = middle1Point.y;
                        var middle2Point = countTailPosition(middle1X, middle1Y, middle2X, middle2Y);
                        middle2X = middle2Point.x;
                        middle2Y = middle2Point.y;
                        var middle3Point = countTailPosition(middle2X, middle2Y, middle3X, middle3Y);
                        middle3X = middle3Point.x;
                        middle3Y = middle3Point.y;
                        var middle4Point = countTailPosition(middle3X, middle3Y, middle4X, middle4Y);
                        middle4X = middle4Point.x;
                        middle4Y = middle4Point.y;
                        var middle5Point = countTailPosition(middle4X, middle4Y, middle5X, middle5Y);
                        middle5X = middle5Point.x;
                        middle5Y = middle5Point.y;
                        var middle6Point = countTailPosition(middle5X, middle5Y, middle6X, middle6Y);
                        middle6X = middle6Point.x;
                        middle6Y = middle6Point.y;
                        var middle7Point = countTailPosition(middle6X, middle6Y, middle7X, middle7Y);
                        middle7X = middle7Point.x;
                        middle7Y = middle7Point.y;
                        var middle8Point = countTailPosition(middle7X, middle7Y, middle8X, middle8Y);
                        middle8X = middle8Point.x;
                        middle8Y = middle8Point.y;
                        var tailPoint = countTailPosition(middle8X, middle8Y, tailX, tailY);
                        tailX = tailPoint.x;
                        tailY = tailPoint.y;
                        visitedByTail.add(tailPoint);
                    }
                }
            }

        }
        System.out.println(visitedByTail.stream().distinct().toList().size());
    }

}

/*
--- Part Two ---
A rope snaps! Suddenly, the river is getting a lot closer than you remember. The bridge is still there,
but some of the ropes that broke are now whipping toward you as you fall through the air!

The ropes are moving too quickly to grab; you only have a few seconds to choose how to arch your body to avoid being hit.
Fortunately, your simulation can be extended to support longer ropes.

Rather than two knots, you now must simulate a rope consisting of ten knots.
One knot is still the head of the rope and moves according to the series of motions.
Each knot further down the rope follows the knot in front of it using the same rules as before.

Using the same series of motions as the above example, but with the knots marked H, 1, 2, ..., 9,
the motions now occur as follows:

== Initial State ==

......
......
......
......
H.....  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)

== R 4 ==

......
......
......
......
1H....  (1 covers 2, 3, 4, 5, 6, 7, 8, 9, s)

......
......
......
......
21H...  (2 covers 3, 4, 5, 6, 7, 8, 9, s)

......
......
......
......
321H..  (3 covers 4, 5, 6, 7, 8, 9, s)

......
......
......
......
4321H.  (4 covers 5, 6, 7, 8, 9, s)

== U 4 ==

......
......
......
....H.
4321..  (4 covers 5, 6, 7, 8, 9, s)

......
......
....H.
.4321.
5.....  (5 covers 6, 7, 8, 9, s)

......
....H.
....1.
.432..
5.....  (5 covers 6, 7, 8, 9, s)

....H.
....1.
..432.
.5....
6.....  (6 covers 7, 8, 9, s)

== L 3 ==

...H..
....1.
..432.
.5....
6.....  (6 covers 7, 8, 9, s)

..H1..
...2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

.H1...
...2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== D 1 ==

..1...
.H.2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== R 4 ==

..1...
..H2..
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

..1...
...H..  (H covers 2)
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

......
...1H.  (1 covers 2)
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

......
...21H
..43..
.5....
6.....  (6 covers 7, 8, 9, s)

== D 1 ==

......
...21.
..43.H
.5....
6.....  (6 covers 7, 8, 9, s)

== L 5 ==

......
...21.
..43H.
.5....
6.....  (6 covers 7, 8, 9, s)

......
...21.
..4H..  (H covers 3)
.5....
6.....  (6 covers 7, 8, 9, s)

......
...2..
..H1..  (H covers 4; 1 covers 3)
.5....
6.....  (6 covers 7, 8, 9, s)

......
...2..
.H13..  (1 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

......
......
H123..  (2 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

== R 2 ==

......
......
.H23..  (H covers 1; 2 covers 4)
.5....
6.....  (6 covers 7, 8, 9, s)

......
......
.1H3..  (H covers 2, 4)
.5....
6.....  (6 covers 7, 8, 9, s)
Now, you need to keep track of the positions the new tail, 9, visits.
 In this example, the tail never moves, and so it only visits 1 position.
 However, be careful: more types of motion are possible than before, so you might want to visually compare your simulated rope to the one above.

Here's a larger example:

R 5
U 8
L 8
D 3
R 17
D 10
L 25
U 20
These motions occur as follows (individual steps are not shown):

== Initial State ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........H..............  (H covers 1, 2, 3, 4, 5, 6, 7, 8, 9, s)
..........................
..........................
..........................
..........................
..........................

== R 5 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........54321H.........  (5 covers 6, 7, 8, 9, s)
..........................
..........................
..........................
..........................
..........................

== U 8 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
................H.........
................1.........
................2.........
................3.........
...............54.........
..............6...........
.............7............
............8.............
...........9..............  (9 covers s)
..........................
..........................
..........................
..........................
..........................

== L 8 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
........H1234.............
............5.............
............6.............
............7.............
............8.............
............9.............
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== D 3 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
.........2345.............
........1...6.............
........H...7.............
............8.............
............9.............
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== R 17 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
................987654321H
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

== D 10 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........s.........98765
.........................4
.........................3
.........................2
.........................1
.........................H

== L 25 ==

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
H123456789................

== U 20 ==

H.........................
1.........................
2.........................
3.........................
4.........................
5.........................
6.........................
7.........................
8.........................
9.........................
..........................
..........................
..........................
..........................
..........................
...........s..............
..........................
..........................
..........................
..........................
..........................

Now, the tail (9) visits 36 positions (including s) at least once:

..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
..........................
#.........................
#.............###.........
#............#...#........
.#..........#.....#.......
..#..........#.....#......
...#........#.......#.....
....#......s.........#....
.....#..............#.....
......#............#......
.......#..........#.......
........#........#........
.........########.........
Simulate your complete series of motions on a larger rope with ten knots. How many positions does the tail of the rope visit at least once?
 */
